permalink: /:year:month:day/:title
url: https://ereoo.github.io/
baseurl: 

# variables
name: QA for People
description: Hi! My name is Vladimir Shekhavtsov and I'm QA engineer and it's my blog.
google_verification: null


# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE"]

# Sass
sass:
  style: :compressed
  sass_dir: _sass

# Markdown
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    disable : true
